#!/usr/bin/env ruby

require 'rubygems'
require 'thor'

class RComp < Thor

  # test

  desc "test", "run one or more tests"
  method_option :all,
    :default => false,
    :aliases => "-a",
    :desc => "run all tests"
  method_option :verbose,
    :default => false,
    :aliases => "-v",
    :desc => "toggle verbose output"

  def test
    puts "test #{options.inspect}"
  end

  # gen
  
  desc "gen", "generate expected output for one or more tests"
  method_option :all,
    :default => false,
    :aliases => "-a",
    :desc => "generate expected output for all tests without it"
  method_option :overwrite,
    :default => false,
    :alieas => "-O",
    :desc => "overwrite expected output file for test if present"

  def gen
    puts "gen #{options.inspect}"
  end

  # print

  desc "print", "print out the content of a test and its expected output"
  method_option :result,
    :default => false,
    :aliases => "-r",
    :desc => "print out the test result in addition to the test content and expected output"

  def print
    puts "print #{options.inspect}"
  end

  # vdiff

  desc "vdiff", "vimdiff a test's expected and actual result"

  def vdiff
    puts "vdiff #{options.inspect}"
  end
end
  
RComp.start
